/**
 * localizedField.js
 *
 * Helpers for displaying bilingual fields generated by AI.
 *
 * AI-generated items carry:
 *   name_en  – English name (always present)
 *   name_am  – Amharic name (present when AI generated it)
 *   name     – canonical English fallback (used everywhere else in the app)
 *
 * At render time call localizedName(item, locale) to get the right string.
 */

import i18n from '@/i18n'

/**
 * Return the display name for an item in the current or given locale.
 *
 * @param {{ name?: string, name_en?: string, name_am?: string }} item
 * @param {string} [locale]  defaults to i18n.language
 * @returns {string}
 */
export function localizedName(item, locale) {
  if (!item) return ''
  const lang = locale || i18n.language || 'en'

  if (lang === 'am') {
    return item.name_am || item.name_en || item.name || ''
  }
  return item.name_en || item.name || ''
}

/**
 * React hook — returns a function that resolves localised names reactively
 * when the language changes. Use inside components.
 */
export function useLocalizedName() {
  // i18n.language is reactive via react-i18next; just expose the helper bound to current lang.
  const lang = i18n.language
  return (item) => localizedName(item, lang)
}
